FROM rocker/tidyverse

WORKDIR /usr/local/src/myscripts
RUN apt-get update && \
    apt-get install -yyy \
        wget && \
        wget https://launchpad.net/ubuntu/+source/icu/70.1-2/+build/23145450/+files/libicu70_70.1-2_amd64.deb && \
        dpkg -i libicu70_70.1-2_amd64.deb

WORKDIR /project
COPY renv.lock renv.lock

RUN mkdir -p renv
COPY .Rprofile .Rprofile
COPY renv/activate.R renv/activate.R
COPY renv/settings.json renv/settings.json

RUN R -e 'options( \
    repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"), \
    HTTPUserAgent = sprintf( \
        "R/%s R (%s)", \
        getRversion(), \
        paste(getRversion(), \
          R.version["platform"], \
          R.version["arch"], \
          R.version["os"]))); \
    renv::restore(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"))'

COPY process.r .
