version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning --dir /oradiskvdb1/redis --dbfilename redis.rdb
    volumes:
      - oradiskvdb1:/oradiskvdb1
    networks:
      - gwas_net
    ports:
      - "6379:6379"

  api:
    image: mrcieu/genotype-phenotype-api:latest
    working_dir: /workspace
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
    volumes:
      - oradiskvdb1:/oradiskvdb1
    networks:
      - gwas_net
    ports:
      - "8000:8000"
    env_file:
      - .env.backend

  frontend:
    image: mrcieu/genotype-phenotype-frontend:latest
    volumes:
      - oradiskvdb1:/oradiskvdb1
      - ./certbot/webroot:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    networks:
      - gwas_net
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/webroot:/var/www/certbot
      - ./certbot/letsencrypt:/etc/letsencrypt
    networks:
      - gwas_net
    command: renew --webroot --webroot-path=/var/www/certbot

volumes:
  oradiskvdb1:
    driver: local
    driver_opts:
      type: none
      device: /oradiskvdb1/
      o: bind

networks:
  gwas_net:
    external: true
