version: "3.9"

services:
  gwas_upload_pipeline:
    image: mrcieu/genotype-phenotype-map:latest
    working_dir: /home/pipeline
    command: ["Rscript", "worker/pipeline_worker.R"]
    volumes:
      - oradiskvdc1:/oradiskvdc1
    env_file:
      - .env.pipeline_worker
    networks:
      - gwas_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  oradiskvdc1:
    driver: local
    driver_opts:
      type: none
      device: /oradiskvdc1/
      o: bind

networks:
  gwas_net:
    external: true
